function [BW_out,properties] = filterRegions(BW_in)
%filterRegions  Filter BW image using auto-generated code from imageRegionAnalyzer app.
%  [BW_OUT,PROPERTIES] = filterRegions(BW_IN) filters binary image BW_IN
%  using auto-generated code from the imageRegionAnalyzer App. BW_OUT has
%  had all of the options and filtering selections that were specified in
%  imageRegionAnalyzer applied to it. The PROPERTIES structure contains the
%  attributes of BW_out that were visible in the App.

% Auto-generated by imageRegionAnalyzer app on 03-Mar-2015
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out, 'Solidity', [0.8, Inf]);
BW_out = bwpropfilt(BW_out, 'EquivDiameter', [10, Inf]);

% Get properties.
properties = regionprops(BW_out, {'Area', 'ConvexArea', 'Eccentricity', 'EquivDiameter', 'Perimeter', 'Solidity'});

% Sort the properties.
properties = sortProperties(properties, 'ConvexArea');

% Uncomment the following line to return the properties in a table.
% properties = struct2table(properties);

hist(properties.EquivDiameter,10)



function properties = sortProperties(properties, sortField)

% Compute the sort order of the structure based on the sort field.
[~,idx] = sort([properties.(sortField)], 'descend');

% Reorder the entire structure.
properties = properties(idx);
