function [fitresult, gof] = createFit1(distScale, cf_x)
%CREATEFIT1(DISTSCALE,CF_X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : distScale
%      Y Output: cf_x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Nov-2015 13:06:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( distScale, cf_x );

% Set up fittype and options.
ft = fittype( 'd*(1-exp(-(x/a)^r))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [3 10 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = loglog( min(xData):0.001:max(xData), fitresult(min(xData):0.001:max(xData)), 'r', xData, yData, 'b.' );
legend( h, 'cf_x vs. distScale', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel distScale
ylabel cf_x
grid on


