function [fig, fitresult, gof] = createFit(xval, cf_x, label, startParam)
%CREATEFIT(XVAL,CF_X)
%  Create a fit.
%
%  Data for 'Direction-Height Correlation Function' fit:
%      X Input : xval
%      Y Output: cf_x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jan-2015 16:30:33

global m_HightTick;

%% Fit: 'Direction-Height Correlation Function'.
[xData, yData] = prepareCurveData( xval, cf_x );

% Set up fittype and options.
ft = fittype( 'd*(1-exp(-(x/a)^r))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% [d a r]
opts.Lower = [0 0 0];
opts.Upper = [Inf Inf Inf];
opts.StartPoint = startParam;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


% Plot fit with data.
fig=figure( 'Name',sprintf('%s-Height Correlation Function', label) );

% Create axes
axes1 = axes('Parent',fig,'YMinorTick','on','YScale','log',...
    'XMinorTick','on',...
    'XScale','log');
%ylim(axes1,[1 20]);
%xlim(axes1,[0.1 100]);
box(axes1,'on');
%hold(axes1,'on');
title({sprintf('%s-Height Correlation Function', label)});
loglog( 0.1:0.001:max(xData), fitresult(0.1:0.001:max(xval)), 'r', xData, yData, 'b.' );
%legend( sprintf('fit function\nroughness=%.2f', fitresult.r), 'measurement', 'Location', 'SouthEast' );
legend( 'fit function', 'measurement', 'Location', 'SouthEast' );
% Create ylabel
ylabel({'<z(r)-z(0)>^2 [nm^2]'});

% Create xlabel
xlabel(sprintf('%s [nm]', label));
grid on


