function [BW,maskedImage] = segmentImage(im)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Nov-2015
%----------------------------------------------------

% Initialize segmentation with Otsu's threshold
level = graythresh(im);
% We use a slightly higher thershhold here
mask = im2bw(im,level*1.14);

% Suppress components connected to image border
BW = imclearborder(mask);

% Filter components by area
BW = bwareafilt(BW, [20 3000]);

% Evolve segmentation
BW = activecontour(im, BW, 40, 'Chan-Vese');

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;
end
